spring:
  application:
    name: item-service
    
server:  port: 8001
  
eureka:  client:    service-url:
    #需要同时向两个eureka注册信息
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka      