spring:
  application:
    name: item-service
  cloud:
     config:
        override-none: true
  rabbitmq:
    host: 192.168.64.130
    port: 5672
    username: admin
    password: admin
         
server:  port: 8001
  
eureka:  client:    service-url:
    #需要同时向两个eureka注册信息
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka      